using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace TeklaLookup.App.Tests;

/// <summary>
/// A throwaway directory tree of <c>.lst</c> files for one test.
/// </summary>
/// <remarks>
/// Tests build their own fixtures rather than reading an installed Tekla environment. The shapes
/// that matter — container files, includes that reach a sibling folder, malformed lines — are all
/// expressible in a few lines, and a suite that only passes on a machine with the right Tekla and
/// the right environment installed is not a suite anyone can rely on. One opt-in test elsewhere
/// covers a real installation when there is one.
/// </remarks>
public sealed class LstFixture : IDisposable
{
    private readonly string _root;

    public LstFixture()
    {
        _root = Path.Combine(Path.GetTempPath(), "TeklaLookupTests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_root);
    }

    /// <summary>Writes a file, creating any intermediate folders. Returns its full path.</summary>
    public string Write(string relativePath, string contents)
    {
        var full = Path.Combine(_root, relativePath);
        var directory = Path.GetDirectoryName(full);
        if (!string.IsNullOrEmpty(directory)) Directory.CreateDirectory(directory!);
        File.WriteAllText(full, contents.Replace("\r\n", "\n").Replace("\n", Environment.NewLine));
        return full;
    }

    public string Dir(string relativePath = "")
    {
        var full = relativePath.Length == 0 ? _root : Path.Combine(_root, relativePath);
        Directory.CreateDirectory(full);
        return full;
    }

    /// <summary>
    /// Builds a well-formed attribute file. <paramref name="definitions"/> are
    /// <c>NAME DATATYPE</c> pairs, <paramref name="bindings"/> are raw binding lines.
    /// </summary>
    public static string File_(
        IEnumerable<string>? definitions = null,
        IEnumerable<string>? bindings = null,
        IEnumerable<string>? includes = null)
    {
        var text = new StringBuilder();
        text.AppendLine("// generated by LstFixture");

        foreach (var include in includes ?? Array.Empty<string>())
            text.AppendLine($"[INCLUDE {include}]");

        foreach (var definition in definitions ?? Array.Empty<string>())
            text.AppendLine(definition);

        text.AppendLine("[BINDINGS] // Do NOT remove this line");

        foreach (var binding in bindings ?? Array.Empty<string>())
            text.AppendLine(binding);

        return text.ToString();
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_root)) Directory.Delete(_root, recursive: true);
        }
        catch (IOException)
        {
            // A leftover temp folder is not worth failing a test over.
        }
    }
}
